### PR TITLE
Implement new NEAR RPC errors decoding

### PR DESCRIPTION
**Pull request by mikroskeem**

### CODE REVIEW

**Review by mllnd — APPROVED** [review]

**Comment by mikroskeem** [comment]
This PR still needs to be tested with various error scenarios from the RPC, e.g transaction timeouts etc.

**Comment by vic-dayou** [comment]
> This PR still needs to be tested with various error scenarios from the RPC, e.g transaction timeouts etc.

When can the test be completed

**Comment by mikroskeem** [comment]
I am unable to get RPC nodes to return errors I want to (tricky on testnet, practically impossible on localnet imo). If anyone manages to give me JSON responses of errors from RPC then that would help a lot already.

**Comment by vic-dayou** [comment]
> I am unable to get RPC nodes to return errors I want to (tricky on testnet, practically impossible on localnet imo). If anyone manages to give me JSON responses of errors from RPC then that would help a lot already.

I don't think timeout needs special handling since it's unpredictable and only needs to handle explicit error types

**Comment by mikroskeem** [comment]
I mean rather about testing overall, not handling specially errors (yet). I wouldn't merge this PR in blindly after testing this with one or two cases.

**Pull request merged**
